### ISSUE TITLE
Can not create documents

### ISSUE THREAD

**Issue by Peeet93** [horstoeko/zugferd-laravel#1] opened 2024-10-10 07:09 UTC
**Describe the bug**
If i try to call this method: `ZugferdLaravel::createDocumentInXRechnung30Profile();` 
i get this error: `Call to protected horstoeko\zugferd\ZugferdDocument::__construct() from scope horstoeko\zugferdlaravel\ZugferdLaravel`

**Additional information:**
 - PHP-Version 8.3

If you make the constructor of ZugpferdDocument public, it is working again

**Comment by horstoeko** [comment] 2024-10-10 07:37
Hi @Peeet93,

thank you for your issue. I've made a fix and a new release v1.0.2. I would be delighted to receive feedback. If the issue is resolved with the new release, please close the issue yourself.

Kind regards

**Closed as completed** 2024-10-13 14:56 UTC
Labels: bug
